server {
    listen 80;
    server_name seu-ip-ou-dominio.com; # Substitua pelo IP da sua VPS ou seu Dominio

    # Tamanho maximo de arquivos para upload na Biblioteca
    client_max_body_size 50M;

    # Localizacao dos Arquivos Estaticos (CSS/JS)
    location /static/ {
        alias /home/{{USER}}/Banco_Ideias/src/static/;
    }

    # Localizacao dos Arquivos de Midia (PDFs da Biblioteca)
    location /media/ {
        alias /home/{{USER}}/Banco_Ideias/assets/media/;
    }

    # Proxy para o Gunicorn (O motor da Digiana)
    location / {
        include proxy_params;
        proxy_pass http://unix:/home/{{USER}}/Banco_Ideias/src/digiana.sock;
        
        # Tempos de espera para processamento de IA
        proxy_read_timeout 120s;
        proxy_connect_timeout 120s;
        proxy_send_timeout 120s;
    }

    # Pagina de erro customizada (Opcional)
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
