# Generated by Django 6.0.3 on 2026-03-26 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ai', '0004_chatmessage_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConsistencyCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_response', models.TextField(help_text='Cópia da resposta original da IA para auditoria.')),
                ('suggested_improvement', models.TextField(help_text='Resposta ideal escrita pelo Superusuário.')),
                ('curated_at', models.DateTimeField(auto_now_add=True)),
                ('is_integrated', models.BooleanField(default=False, help_text='Marcar quando o RAG absorver esta melhoria.')),
                ('curated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_corrections', to=settings.AUTH_USER_MODEL)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='chat_ai.chatmessage')),
            ],
            options={
                'verbose_name': 'Correção de Consistência IA',
                'verbose_name_plural': 'Correções de Consistência IA',
                'ordering': ['-curated_at'],
            },
        ),
    ]
