# Generated by Django 6.0.3 on 2026-04-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ai', '0006_alter_chatsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconsistencycorrection',
            name='titulo_melhoria',
            field=models.CharField(blank=True, help_text='Título resumido para organização (ex: Regra de IRPJ).', max_length=255),
        ),
    ]
