# Generated by Django 6.0.3 on 2026-04-01 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ai', '0007_aiconsistencycorrection_titulo_melhoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconsistencycorrection',
            name='user_query',
            field=models.TextField(blank=True, help_text='Pergunta original do usuário para contexto perpétuo.'),
        ),
        migrations.AlterField(
            model_name='aiconsistencycorrection',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction', to='chat_ai.chatmessage'),
        ),
    ]
