# Generated by Django 6.0.3 on 2026-04-01 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ai', '0008_aiconsistencycorrection_user_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconsistencycorrection',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='chat_ai.chatmessage'),
        ),
    ]
