# Generated by Django 6.0.3 on 2026-03-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalideia',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
