# Generated by Django 6.0.3 on 2026-03-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_ativa_to_globalideia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAnagma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil Anagma',
            },
        ),
    ]
