# Generated by Django 6.0.3 on 2026-03-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilanagma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['nome_completo', 'username']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('paused', 'Pausado')], default='active', max_length=10),
        ),
    ]
