# Generated by Django 6.0.3 on 2026-03-27 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_options_customuser_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='biblioteca/documentos/')),
                ('extensao', models.CharField(max_length=10)),
                ('conteudo_extraido', models.TextField(blank=True, help_text='Texto bruto extraído via OCR/Parsing')),
                ('resumo_ia', models.TextField(blank=True, help_text='Resumo inicial gerado pela IA para triagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente de Auditoria'), ('approved', 'Aprovado (Na Memória)'), ('rejected', 'Rejeitado (Conteúdo Irrelevante)')], default='pending', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('auditado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_auditados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento da Biblioteca',
                'verbose_name_plural': 'Documentos da Biblioteca',
                'ordering': ['-criado_em'],
            },
        ),
    ]
