# Generated by Django 6.0.3 on 2026-03-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_documentobiblioteca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalideia',
            name='ativa',
            field=models.BooleanField(default=False),
        ),
    ]
