# Generated by Django 6.0.3 on 2026-04-01 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_globalideia_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentobiblioteca',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL),
        ),
    ]
