# Generated by Django 6.0.3 on 2026-04-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_documentobiblioteca_enviado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_preferido', models.CharField(choices=[('LEVE', 'Digiana - LEVE (GGUF)'), ('COMPLETO', 'Digiana - COMPLETO (Safetensors)')], default='LEVE', max_length=10)),
                ('modelo_em_uso', models.CharField(choices=[('LEVE', 'Digiana - LEVE (GGUF)'), ('COMPLETO', 'Digiana - COMPLETO (Safetensors)')], default='LEVE', max_length=10)),
                ('status', models.CharField(choices=[('PRONTO', 'Pronto para Uso'), ('CARREGANDO', 'Carregando...'), ('ERRO', 'Erro no Carregamento'), ('HIBERNACAO', 'Em Hibernação (Fallback)')], default='PRONTO', max_length=15)),
                ('etapa_nome', models.CharField(default='Sistema Estável', help_text='Mensagem amigável para o Admin', max_length=100)),
                ('progresso', models.IntegerField(default=100, help_text='0 a 100 para a barra de progresso')),
                ('ultimo_erro', models.TextField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da IA',
                'verbose_name_plural': 'Configurações da IA',
            },
        ),
    ]
