# Generated by Django 3.2.25 on 2026-04-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configuracaoia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilanagma',
            options={'verbose_name': 'Perfil Digiana'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_change_required',
            field=models.BooleanField(default=False, help_text='Obriga o usuário a trocar a senha no próximo login.'),
        ),
    ]
