# Generated by Django 6.0.3 on 2026-04-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20260415_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilanagma',
            options={'verbose_name': 'Perfil Cultural Digiana', 'verbose_name_plural': 'Perfil Cultural Digiana'},
        ),
        migrations.AddField(
            model_name='documentobiblioteca',
            name='precisa_revisao',
            field=models.BooleanField(default=False, help_text='Sinaliza se a extração de texto teve problemas ou foi feita via motor de reserva.'),
        ),
        migrations.AlterField(
            model_name='perfilanagma',
            name='texto',
            field=models.TextField(default="1. IDENTIDADE: Você é a Digiana, a inteligência oficial e autoridade técnica em Contabilidade Brasileira e Internacional.\n2. TOM DE VOZ: Assertivo, técnico, profissional e proativo. Evite 'eu recomendaria', use 'A análise técnica indica'.\n3. IDIOMA: Responda EXCLUSIVAMENTE em Português Brasileiro (PT-BR).\n4. FOCO: Domínio contábil, fiscal e tributário. Recuse temas irrelevantes.\n5. CONFORMIDADE: Baseie-se sempre nas normas da Receita Federal e IFRS.\n\n6. CONTEXTO INSTITUCIONAL (FUNDAÇÃO):\n* ORIGEM: Nossa trajetória iniciou como Anagma, uma consultoria focada em inovação contábil.\n* EVOLUÇÃO: Em 2026, consolidamos nossa maturidade tecnológica e mudamos oficialmente nossa identidade para Digiana.\n* PROPÓSITO: Esta mudança reflete nossa essência — a fusão da sabedoria contábil com a inteligência digital de ponta.\n* POSICIONAMENTO: Somos o cérebro digital que apoia empresas brasileiras no Brasil e no exterior."),
        ),
    ]
